name: Deploy to GitHub Pages

on:
  push:
    branches: [ gh-pages ]  # 监听 main 分支的推送

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 安装 Node.js（若需构建）
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.0

      # 3. 安装依赖并构建（示例为前端项目）
      - name: Install & Build
        run: |
          npm install
          npm run build  # 生成静态文件到 dist/ 目录

      # 4. 部署到 Pages 分支
      - name: Deploy
        uses: github-pages-test/gh-pages
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 自动生成的 Token
          branch: gh-pages    # 目标 Pages 分支
          folder: dist        # 构建后的目录
          force: true         # 强制覆盖历史提交