name: Deploy to GH Pages
on:
  push:
    branches: [main]  # 监控这个分支的推送
    branches-ignore:       # 显式忽略 gh-pages
      - gh-pages

permissions:
  contents: write  # 添加这个权限声明

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用 GitHub 的虚拟环境
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # 克隆你的仓库

      - name: Install and Build
        run: |  # 在此环境中构建
          npm install
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub 自动提供的密钥
          publish_dir: ./dist  # 要发布的目录
          commit_message: "Deploy: ${{ github.sha }} [skip ci]"  # 防止触发新工作流
          force_orphan: true